"""
Intain Loan Performance Intelligence Engine
Synthetic Data Generator - Monthly Test Dataset

Generates:
    data/synthetic/loan_monthly_performance_test.csv

Important:
    This dataset intentionally contains NO target labels.

    The test set contains only observable loan/month features.
    Predictions will later be generated by the ML pipeline.

Development data only.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 123
END_DATE = pd.Timestamp("2026-07-01")

INPUT_FILE = Path(
    "data/synthetic/loan_static_attributes.csv"
)

OUTPUT_DIR = Path("data/synthetic")

OUTPUT_FILE = (
    OUTPUT_DIR /
    "loan_monthly_performance_test.csv"
)

rng = np.random.default_rng(SEED)


# ============================================================
# REFERENCE VALUES
# ============================================================

SOURCE_SYSTEMS = [
    "ServicingCore",
    "LoanPlatform",
    "RiskSystem"
]

DOCUMENT_STATUSES = [
    "Complete",
    "Complete",
    "Complete",
    "Pending",
    "Missing"
]


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def band_to_midpoint(value: str) -> float:

    mapping = {
        "580-619": 600,
        "620-659": 640,
        "660-699": 680,
        "700-739": 720,
        "740-779": 760,
        "780+": 790
    }

    return mapping[value]


def ltv_midpoint(value: str) -> float:

    mapping = {
        "0-60": 55,
        "60-70": 65,
        "70-80": 75,
        "80-90": 85,
        "90-100": 95
    }

    return mapping[value]


def dti_midpoint(value: str) -> float:

    mapping = {
        "0-20": 15,
        "20-30": 25,
        "30-40": 35,
        "40-50": 45
    }

    return mapping[value]


def logistic(x):

    x = np.clip(x, -20, 20)

    return 1 / (
        1 + np.exp(-x)
    )


def calculate_risk(loan):

    credit_score = band_to_midpoint(
        loan["credit_score_band"]
    )

    ltv = ltv_midpoint(
        loan["ltv_band"]
    )

    dti = dti_midpoint(
        loan["dti_band"]
    )

    credit_risk = (
        720 - credit_score
    ) / 120

    ltv_risk = (
        ltv - 60
    ) / 40

    dti_risk = (
        dti - 20
    ) / 30

    return (
        0.45 * credit_risk
        + 0.30 * ltv_risk
        + 0.25 * dti_risk
    )


def generate_balance(
    original_balance,
    annual_rate,
    age_months,
    term_months
):

    monthly_rate = (
        annual_rate / 100 / 12
    )

    if monthly_rate == 0:

        balance = (
            original_balance
            * (
                1
                - age_months / term_months
            )
        )

    else:

        payment = (
            original_balance
            * monthly_rate
            * (1 + monthly_rate) ** term_months
            / (
                (1 + monthly_rate) ** term_months
                - 1
            )
        )

        balance = (
            original_balance
            * (1 + monthly_rate) ** age_months
            - payment
            * (
                (
                    (1 + monthly_rate) ** age_months
                    - 1
                )
                / monthly_rate
            )
        )

    return np.clip(
        balance,
        0,
        original_balance
    )


# ============================================================
# GENERATE ONE LOAN
# ============================================================

def generate_loan_test_history(
    loan
):

    loan_id = loan["loan_id"]

    origination_month = pd.Timestamp(
        loan["origination_month"]
    )

    original_balance = float(
        loan["original_balance"]
    )

    interest_rate = float(
        loan["interest_rate"]
    )

    term_months = int(
        rng.choice(
            [180, 240, 300, 360],
            p=[0.05, 0.15, 0.15, 0.65]
        )
    )

    risk = calculate_risk(
        loan
    )

    reporting_months = pd.date_range(
        start=origination_month,
        end=END_DATE,
        freq="MS"
    )

    records = []

    previous_dpd = 0
    previous_status = "Current"

    for month_index, reporting_month in enumerate(
        reporting_months
    ):

        if month_index >= term_months:
            break

        # A loan that has already default or prepaid has terminated
        if previous_status in {"Default", "Prepaid"}:
            break

        loan_age = month_index

        remaining_term = (
            term_months
            - loan_age
        )

        # ----------------------------------------------------
        # Base balance
        # ----------------------------------------------------

        current_balance = generate_balance(
            original_balance,
            interest_rate,
            loan_age,
            term_months
        )

        # ----------------------------------------------------
        # Generate observable performance
        # ----------------------------------------------------

        # If previous status is Delinquent, default is much more likely
        default_base = -5.0
        if previous_status == "Delinquent":
            if previous_dpd == 90:
                default_base = -1.2
            elif previous_dpd == 60:
                default_base = -2.5
            else:
                default_base = -4.0

        default_probability = logistic(
            default_base
            + 2.0 * risk
            + (0.15 if loan_age > 24 else 0)
        )

        prepayment_probability = logistic(
            -3.2
            - 0.7 * risk
            + (0.4 if loan_age > 18 else 0)
        )

        delinquency_probability = logistic(
            -3.8
            + 1.8 * risk
            + (1.5 if previous_status == "Delinquent" else 0)
        )

        random_value = rng.random()

        # Determine next DPD and status
        prepayment_flag = 0
        modification_flag = 0

        if random_value < default_probability:
            dpd = 90
            current_status = "Default"
            modification_flag = int(rng.random() < 0.10)
        elif (previous_status != "Delinquent" or previous_dpd <= 30) and rng.random() < prepayment_probability * 0.15:
            dpd = 0
            current_status = "Prepaid"
            prepayment_flag = 1
            current_balance = round(
                current_balance
                * rng.uniform(0.0, 0.08),
                2
            )
        elif random_value < (default_probability + delinquency_probability):
            # Roll DPD logically based on credit transition roll-rates
            if previous_dpd == 0:
                dpd = 30
            else:
                roll_rand = rng.random()
                if previous_dpd == 30:
                    if roll_rand < 0.60:
                        dpd = 60
                    elif roll_rand < 0.90:
                        dpd = 30
                    else:
                        dpd = 0
                elif previous_dpd == 60:
                    if roll_rand < 0.70:
                        dpd = 90
                    elif roll_rand < 0.90:
                        dpd = 60
                    else:
                        dpd = 30
                else:  # previous_dpd == 90
                    if roll_rand < 0.80:
                        dpd = 90
                    else:
                        dpd = 60
            
            if dpd == 90:
                current_status = "Default"
            elif dpd > 0:
                current_status = "Delinquent"
            else:
                current_status = "Current"
            
            modification_flag = int(dpd >= 60 and rng.random() < 0.08)
        else:
            dpd = 0
            current_status = "Current"
            modification_flag = int(rng.random() < 0.02)

        # ----------------------------------------------------
        # Document/source information
        # ----------------------------------------------------

        source_system = rng.choice(
            SOURCE_SYSTEMS,
            p=[0.60, 0.25, 0.15]
        )

        document_status = rng.choice(
            DOCUMENT_STATUSES
        )

        last_updated_at = (
            reporting_month
            + pd.Timedelta(
                days=int(
                    rng.integers(
                        1,
                        28
                    )
                )
            )
            + pd.Timedelta(
                hours=int(
                    rng.integers(
                        0,
                        24
                    )
                )
            )
        )

        records.append({

            "loan_id":
                loan_id,

            "month_index":
                month_index,

            "reporting_month":
                reporting_month,

            "origination_month":
                origination_month,

            "loan_age_months":
                loan_age,

            "remaining_term_months":
                remaining_term,

            "original_balance":
                round(
                    original_balance,
                    2
                ),

            "current_balance":
                round(
                    current_balance,
                    2
                ),

            "interest_rate":
                round(
                    interest_rate,
                    3
                ),

            "credit_score_band":
                loan["credit_score_band"],

            "ltv_band":
                loan["ltv_band"],

            "dti_band":
                loan["dti_band"],

            "state":
                loan["state"],

            "loan_purpose":
                loan["loan_purpose"],

            "occupancy_type":
                loan["occupancy_type"],

            "property_type":
                loan["property_type"],

            "servicer_name":
                loan["servicer_name"],

            "current_status":
                current_status,

            "days_past_due":
                dpd,

            "modification_flag":
                modification_flag,

            "prepayment_flag":
                prepayment_flag,

            "loss_severity_band":
                "None",

            "last_updated_at":
                last_updated_at,

            "source_system":
                source_system,

            "document_status":
                document_status
        })

        previous_dpd = dpd
        previous_status = current_status

    return records


# ============================================================
# VALIDATION
# ============================================================

def validate_test_data(df):

    print("\nRunning test-data validation...")

    # --------------------------------------------------------
    # No target columns allowed
    # --------------------------------------------------------

    forbidden_target_columns = [
        "next_3m_delinquency_flag",
        "next_6m_delinquency_flag",
        "next_12m_default_flag",
        "next_12m_prepayment_flag",
        "next_state",
        "exception_required",
        "exception_type"
    ]

    found_targets = [
        column
        for column in forbidden_target_columns
        if column in df.columns
    ]

    assert not found_targets, (
        f"Test dataset contains target columns: "
        f"{found_targets}"
    )

    # --------------------------------------------------------
    # Positive original balance
    # --------------------------------------------------------

    assert (
        df["original_balance"] > 0
    ).all()

    # --------------------------------------------------------
    # Valid current balance
    # --------------------------------------------------------

    assert (
        df["current_balance"] >= 0
    ).all()

    assert (
        df["current_balance"]
        <= df["original_balance"]
    ).all()

    # --------------------------------------------------------
    # Valid interest rates
    # --------------------------------------------------------

    assert (
        df["interest_rate"]
        .between(0, 15)
        .all()
    )

    # --------------------------------------------------------
    # Valid DPD
    # --------------------------------------------------------

    assert (
        df["days_past_due"]
        .isin(
            [0, 30, 60, 90]
        )
        .all()
    )

    # --------------------------------------------------------
    # Valid binary values
    # --------------------------------------------------------

    for column in [
        "modification_flag",
        "prepayment_flag"
    ]:

        assert set(
            df[column].unique()
        ).issubset(
            {0, 1}
        )

    # --------------------------------------------------------
    # Date relationship
    # --------------------------------------------------------

    assert (
        df["reporting_month"]
        >= df["origination_month"]
    ).all()

    assert (
        df["reporting_month"]
        <= END_DATE
    ).all()

    # --------------------------------------------------------
    # Loan age
    # --------------------------------------------------------

    assert (
        df["loan_age_months"] >= 0
    ).all()

    # --------------------------------------------------------
    # Remaining term
    # --------------------------------------------------------

    assert (
        df["remaining_term_months"] >= 0
    ).all()

    print(
        "Test-data validation PASSED."
    )


# ============================================================
# MAIN
# ============================================================

def main():

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    print("=" * 70)
    print(
        "INTAIN SYNTHETIC TEST DATA GENERATOR"
    )
    print("=" * 70)

    # --------------------------------------------------------
    # Load static loans
    # --------------------------------------------------------

    static_df = pd.read_csv(
        INPUT_FILE,
        parse_dates=[
            "origination_month"
        ]
    )

    print(
        f"Static loans loaded: "
        f"{len(static_df):,}"
    )

    # --------------------------------------------------------
    # Generate monthly records
    # --------------------------------------------------------

    all_records = []

    print("\nProcessing loan historical paths...")
    for index, loan in tqdm(static_df.iterrows(), total=len(static_df), desc="Generating Monthly Test Performance", bar_format="{l_bar}{bar:30}{r_bar}"):

        records = (
            generate_loan_test_history(
                loan
            )
        )

        all_records.extend(
            records
        )

    df = pd.DataFrame(
        all_records
    )

    # --------------------------------------------------------
    # Sort
    # --------------------------------------------------------

    df = df.sort_values(
        [
            "loan_id",
            "reporting_month"
        ]
    ).reset_index(
        drop=True
    )

    # --------------------------------------------------------
    # Validate
    # --------------------------------------------------------

    validate_test_data(
        df
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print("\n" + "=" * 70)
    print(
        "TEST DATA GENERATED SUCCESSFULLY"
    )
    print("=" * 70)

    print(
        f"Rows         : {len(df):,}"
    )

    print(
        f"Columns      : {len(df.columns)}"
    )

    print(
        f"Unique loans : "
        f"{df['loan_id'].nunique():,}"
    )

    print(
        f"Date range   : "
        f"{df['reporting_month'].min().date()} "
        f"→ "
        f"{df['reporting_month'].max().date()}"
    )

    print(
        f"Output       : "
        f"{OUTPUT_FILE}"
    )

    print(
        "\nTarget columns: NONE"
    )

    print("\nSample:")
    print(
        df.head()
    )


if __name__ == "__main__":
    main()